### PR TITLE
feat: apply and clean publishConfig in package.json

### PR DESCRIPTION
**Pull request by dangreen**
BREAKING CHANGE: `--exports` option was removed, same result can be achieved with `publishConfig`

### CODE REVIEW

**Comment by ai** [comment]
Can you explain the reasons behind these changes and why we need to remove `exports`?

**Comment by dangreen** [comment]
@ai 

For example, pnpm applies fields from publishConfig but doesn't remove them after it.

source:

```json
{
  "main": "./src/index.ts",
  "types": "./dist/index.d.ts",
  "publishConfig": {
    "main": "./dist/index.cjs",
    "module": "./dist/index.js",
    "exports": {
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    },
    "directory": "package"
  }
}
```

pnpm:

```json
{
  "main": "./dist/index.cjs",
  "types": "./dist/index.d.ts",
  "publishConfig": {
    "main": "./dist/index.cjs",
    "module": "./dist/index.js",
    "exports": {
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    },
    "directory": "package"
  },
  "module": "./dist/index.js",
  "exports": {
    "import": "./dist/index.js",
    "require": "./dist/index.cjs"
  }
}
```

clean-publish:

```json
{
  "main": "./dist/index.cjs",
  "types": "./dist/index.d.ts",
  "publishConfig": {
    "directory": "package"
  },
  "module": "./dist/index.js",
  "exports": {
    "import": "./dist/index.js",
    "require": "./dist/index.cjs"
  }
}
```

**Comment by ai** [comment]
DO you mean that now instead of `--exports` option we will use `package.publishConfig.exports`?

**Comment by dangreen** [comment]
@ai yes

**Pull request merged**
