### PR TITLE
Ignore prepare script

### PR DESCRIPTION
**Pull request by azat-io**

### CODE REVIEW

**Comment by ai** [comment]
Are you sure that `prepare` does not right on `npm install` of some npm package?

https://docs.npmjs.com/cli/v10/using-npm/scripts#prepare-and-prepublish

**Comment by azat-io** [comment]
I read somewhere that the “prepare” script is executed after the dependencies are installed, but before the bin is moved to `.bin`.

But maybe I'm wrong. I need to solve this problem somehow at the moment. And I thought that `prepare` script will help me with it.

**Comment by ai** [comment]
What problem are you trying to solve? If you have some development script in your project you need to use `prepublishOnly` instead

**Comment by azat-io** [comment]
I have several binaries for different operating systems.

For example, I have `package/build/linux/my-bin`, `package/build/windows/my-bin`.

After installing the npm package, I move the binary to the `package/bin` folder.

After that, npm should move the executable to `node_modules/.bin`. I can't use `postinstall` because it happens already after this move of the executable.

**Comment by ai** [comment]
Got it, you want to keep this script and now remove it.

Sure.

**Comment by ai** [comment]
Released in 5.1.

**Pull request merged**
